server:
  port: 13000



client:
  url:
    schema: http
    hostname: localhost
    port: 12000
    path: /v1/student

spring:
  profiles:
    active: basic

---
spring:
  profiles: basic

resource:
  server:
    user: student
    password: dXNlcjo2N2VlM2IzZC1iODRmLTQxYzgtOWUxMS01ZTg3ZjAwNTE3MWY=